### ISSUE TITLE
Food Tracker

### ISSUE THREAD

**Issue by yekenuk** [yekenuk/Weight-Tracker#175]
The ability to track food eaten during the day with calorie amounts. [To be expanded and defined further]

**Comment by worldsdream** [comment]
The most beloved feature. Would love to help you with this one. Let me know.

**Comment by yekenuk** [comment]
Yeah, will do! I need to look into the best tool to allow everyone interested in it to feed their ideas in. I've a feeling that will be the toughest bit! Building something that suits most!

**Comment by yekenuk** [comment]
Noting this URL here as a good example:

http://www.eatthismuch.com/

**Comment by ch-schroeder** [comment]
Hi, whats about this feature? Definitely the most beloved feature!

**Comment by yekenuk** [comment]
Ah I'm really wanting to get this done @ch-schroeder! Even started developing a separate plugin! Right now, I'm needing to focus on paying projects :( Would love to complete this!

**Comment by yekenuk** [comment]
This currently in progress as a new plugin :)

**Comment by yekenuk** [comment]
I'm closing this issue as version 1 is nearly ready!

If you wish to be updated upon its release, please email me directly email@yeken.uk
