### ISSUE TITLE
Date of Birth - 0 years old

### ISSUE THREAD

**Issue by mybestrong** [yekenuk/Weight-Tracker#215]
We get members who choose the current year as their date of birth from the date picker, then there's no BMI calculated etc, but the wizard tells them they're all up to date with their data.. Maybe an error message if they choose a date of birth which makes them 0 years of age :)

**Comment by mybestrong** [comment]
Hi Ali,

Is there any update on a timescale for this one? We still get members caught in a loop within the wizard if they select the incorrect dob.

**Comment by yekenuk** [comment]
This has been fixed. Will be in the next release.
