### ISSUE TITLE
Shortcode removed??

### ISSUE THREAD

**Issue by PascalPoeck** [yekenuk/Weight-Tracker#251]
Hello,

I'm using the shortcode [wpc_progress_bar course=""] for a while now and recently I had to modify my page. When I saved the page again the shortcode stop working like in the picture in attachment.

![Capture](https://user-images.githubusercontent.com/14034752/73653611-dd91b880-4689-11ea-8655-e4205554e391.PNG)

I took a look in the documentation and it seems this parameter course="" is not used anymore but it's still working for other "non modified" pages so does I miss something?

**Comment by yekenuk** [comment]
[wpc_progress_bar] isn't a Weight Tracker shortcode. This belongs to another (non-YeKen) plugin.
