### ISSUE TITLE
User settings empty

### ISSUE THREAD

**Issue by PascalPoeck** [yekenuk/Weight-Tracker#252]
Hello,

It seems that the user settings are not saved anymore. Each time a user try to save them, they turn blank again and again...

![Capture](https://user-images.githubusercontent.com/14034752/73653803-6f012a80-468a-11ea-87d2-3df32866898d.PNG)

I have the Pro licence and several hundreds users so imagine my mailbox right now... 
Thanks for your help.

**Comment by yekenuk** [comment]
Hi there,

Sorry for the inconvenience. This should hopefully be fixed in 7.5.4 that has just gone out the door.

Cheers,

Ali
